# Generated by Django 3.0.5 on 2022-06-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientDischargeDetails',
        ),
    ]
